version: '3'
services:
  web:
    image: web:latest
    volumes:
     - D:/program/demo_shopping_mall/volume/web:/volume/web
    ports:
     - 5000:3000
  redis:
    image: redis:latest
    volumes: 
      - D:/program/demo_shopping_mall/volume/redis:/volume/redis
  postgres:
    image: postgres:latest
    ports:
     - 15320:5432
    networks:
      mynet:
        ipv4_address: '179.19.0.12'
    environment:
        POSTGRES_PASSWORD: dsm123  
    volumes:
      - pgdata:/var/lib/postgresql:Z

networks:
  mynet:
    ipam:
      driver: default
      config:
        - subnet: 179.19.0.0/16

volumes:
    pgdata:
      driver_opts:
        type: none
        device: D:\program\demo_shopping_mall\volume\postgres\pgdata
        o: bind