version: '3'
services:
  web:
    image: web:latest
    volumes:
     - D:/program/demo_shopping_mall/volume/web:/volume/web
    ports:
     - 5000:3000
  redis:
    image: redis:latest
    volumes: 
      - D:/program/demo_shopping_mall/volume/redis:/volume/redis
    ports:
     - 7145:6379
  postgres:
    image: postgres:latest
    ports:
      - "15320:5432"
    environment:
      POSTGRES_DB: demo_shopmall_test
      POSTGRES_USER: demo_shopmall
      POSTGRES_PASSWORD: dsm123
    volumes:
      - pgdata:/var/lib/postgresql:Z

volumes:
    pgdata:
      external: true